[package]
name = "libcudf-datafusion-benchmarks"
version = "0.1.0"
edition = "2021"
default-run = "dfbench"
authors = [
    "notfilippo",
    "gabotechs",
    "jayshrivastava",
    "gene-bordegaray",
]

[dependencies]
libcudf-datafusion = { path = "../libcudf-datafusion" }
arrow = { workspace = true }
datafusion = "55"
datafusion-expr = "55"
datafusion-physical-plan = "55"
tokio = { version = "1.41", features = ["full"] }
parquet = { version = "59" }
structopt = "0.3.26"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = "0.11"
futures = "0.3"
rusqlite = { version = "0.37", features = ["bundled"] }
tpchgen = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "b265283f5c765b96731b6d6d4317298b7bb4be07" }
tpchgen-arrow = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "b265283f5c765b96731b6d6d4317298b7bb4be07" }
reqwest = "0.12"
zip = "6.0"

[[bin]]
name = "dfbench"
path = "src/main.rs"

[lints]
workspace = true
